#!/bin/sh

local hdir bkdir rbkdir ropts

nback ()
{
    local name bdir
    name=$1
    bdir=$2
    shift 2
    tar -jcf "$bkdir/$name.tar.bz2" -C "$bdir" "$@" || echo "Backup $name failed" >&2;
}

hdir="${SHOME:-$HOME}"

[ -r "$hdir/.backup" ] || return 0

. "$hdir/.backup" || return 0

bkdir="${bkdir:-${TMPDIR:-/tmp}}"

if [ -n "$rbkdir" ]; then
    [ -n "$NOSCP" ] || scp -Bq "$ropts" "$bkdir"/* "$rbkdir"
fi

unset -f nback
