#!/bin/zsh

emulate -L zsh

setopt extendedglob

local entries subdirs files subdir file

[[ -n "$1" ]] && set -- ${1%%/#}/
entries=(${(M)${(f)"$(<${1}CVS/Entries)"}:#*/*/*})
subdirs=(${${${(M)entries:#D*}#*/}%%/*})
files=(${${${entries}#*/}%%/*})
for file in $1.#*~${1}CVS(N:t); do
    [[ ${#${(M)files:#${(q)file}}} -eq 0 ]] && echo $1$file
done
for subdir in $subdirs; do
    $0 $1$subdir
done
