#!/bin/sh
#Small script to initialize all files/dirs recursively to sane permissions.

[ $# -eq 0 ] && set -- .

local dir

for dir in "$@"; do
    find "$dir" -type f -print0 | xargs -0 chmod 644
    find "$dir" -type d -print0 | xargs -0 chmod 755
done
