#!/bin/sh
# A simple script to change the read/write mode of mounted devices
# Especially useful for removable media

local ret=0 dev mode=rw

if [ "$1" = -u ]; then
    mode=ro
    shift
fi

if [ -z "$1" ]; then
    echo Usage: $0 '[-u]' '{DEVICE|MOUNTPOINT}'... >&2
    return 127
fi

for dev in "$@"; do
    if [ $mode = ro ] && sudo fuser -mv "$dev"; then
	echo The above processes seem to be using the device $dev, not unplugging...
	ret=`expr $ret + 1`
	continue
    fi
    sudo mount -oremount,$mode "$dev"
done

return $ret
