#!/bin/zsh
# Queues TamilNapster music downloads on d4x.

local i url
typeset -a opts

opts=()
[[ -n "$3" ]] && opts=(-d ${${3:#[^/]*}:-~/downloads/$3})

for ((i=$1;i<=$2;i++)); do
    url="http://www.tamilnapster.com/download.php?id=$i"
    d4x "${opts[@]}" "$url"
done
