#!/bin/sh
# Moves one file to another while retaining any id3 tags originally present

if [ $# -ne 2 ]; then
    echo Usage: $0 '<infile>' '<outfile>' >&2
    return 1
fi

copytag "$1" "$2" && mv "$2" "$1"
