#!/bin/sh
# Using a config file, print shell code to update proxy environment variables

local CFILE

if [ -n "$1" ]; then
    CFILE="$1"
elif [ -n "$SHOME" ]; then
    CFILE="$SHOME/.proxy"
else
    CFILE="$HOME/.proxy"
fi

unset PROXY http_proxy https_proxy ftp_proxy HTTP_PROXY \
    HTTPS_PROXY FTP_PROXY NO_PROXY no_proxy

[ -r "$CFILE" ] || return 0

. "$CFILE" || return 0

prvar () {
    if [ -n "$2" ]; then
	echo export "$1"="$2"\;
    else
	echo unset "$1"\;
    fi
}

prvar http_proxy "${http_proxy:=$PROXY}"
prvar https_proxy "${https_proxy:=$PROXY}"
prvar ftp_proxy "${ftp_proxy:=$PROXY}"
prvar HTTP_PROXY "${HTTP_PROXY:=$PROXY}"
prvar HTTPS_PROXY "${HTTPS_PROXY:=$PROXY}"
prvar FTP_PROXY "${FTP_PROXY:=$PROXY}"
prvar NO_PROXY "$NO_PROXY"
prvar no_proxy "$NO_PROXY"

unset -f prvar
