#!/bin/sh
# Wrapper for mencoder to convert a vcd to an mpg file.

if [ $# -ne 1 ]; then
    echo Usage: $0 '<output file>' >&2
    exit 1
fi

mencoder vcd:// -o "$1" -vf hqdn3d -of mpeg \
    -oac lavc -ovc lavc -lavcopts abitrate=64
