#!/bin/bash
# Wrapper around `display' to display mp3 files as the APIC picture tags in it.
# Uses id3pic, a program to dump APIC pictures in ID3 tagged files.

declare -a args

rm -f /tmp/.display-*.[mM][pP]3.*
for i in "$@"; do
    if echo $i | grep -i "^[^-].*\.mp3$" > /dev/null 2>&1; then
	FPREF=`echo $i | tr / _`
	FPREF="/tmp/display$FPREF."
	id3pic -p "$FPREF" "$i"
	args=("${args[@]}" "$FPREF"*)
    else
	args=("${args[@]}" "$i")
    fi
done
/usr/bin/display "${args[@]}"
rm -f /tmp/.display-*.[mM][pP]3.*
