#!/bin/bash
# Checks differences in filestamps between files in the current directory and an
# another specified directory.

CHECK="$1"
shift

for i in "$@"; do
    OSZ=`stat -c "%s" "$i"`
    NSZ=`stat -c "%s" "$CHECK/$i"`
    [ $OSZ -ne $NSZ ] && echo $i
done
