#!/bin/bash
# Hook script to manage a media centric desktop.

trap "kill \$! > /dev/null 2>&1; exit 1" HUP TERM QUIT INT PIPE

SCRDIR=/home/ramk/scripts

$SCRDIR/mposd
$SCRDIR/id3pic-display "$1"

while true; do
    $SCRDIR/id3less "$1" & wait
    ncmpc
done
