#!/bin/bash
# Hook script to manage a media centric desktop.

trap "kill \$! > /dev/null 2>&1; exit 1" HUP TERM QUIT INT PIPE

mposd
id3pic-display "$1"

while true; do
    id3less "$1" & wait
    ncmpc
done
