#!/bin/bash
# Hook script to manage a media centric desktop.

trap "kill \$! > /dev/null 2>&1; exit 1" HUP TERM QUIT INT PIPE

id3pic-display "$1"

if [ "x$1" == "x" ]; then
    clear
    exit 0
fi

mposd

while true; do
    id3less "$1" & wait
    ncmpc
done
