#!/usr/bin/perl
# Sanitizes lyrics html pages from http://www.nanjil.com

use strict;
use warnings;

while (<>) {
    next unless /<!--HTML--><!--HEAD-->/;
    print;
    while (<>) {
	print;
	last if /<!--\/BODY--><!--\/HTML-->/;
    }
}
