#!/usr/bin/perl
# Scans mpd logs for added songs, printing them in descending order of
# appearance in the log.

use strict;
use warnings;

my @new= ();
while (<>) {
    push @new, $1 if /\w+\s+\d+\s+\d+:\d+\s+:\s+added (.*)/;
}
print pop @new, "\n" while @new;
