#!/bin/sh
#Small script to initialize all files/dirs recursively to sane permissions.

local dir

dir="$1"

[ -z "$dir" ] && dir=.

find "$dir" -type f -print0 | xargs -0 chmod 644
find "$dir" -type d -print0 | xargs -0 chmod 755
