#!/bin/sh
#Small script to initialize all files/dirs recursively to sane permissions.

DIR="$1"

[ -z "$DIR" ] && DIR=.

find "$DIR" -type f -print0 | xargs -0 chmod 644
find "$DIR" -type d -print0 | xargs -0 chmod 755
