#!/bin/sh
# Extracts pictures from nowrunning.com

for i in "$@"; do
    IFILE="http://nowrunning.com/movieStills.asp?lang=$i"
    wget "$IFILE" -q -O - 2> /dev/null | tee "$i-ihtml" | \
	sed -u "s,http://nowrunning\\.com/film/slideshow1.asp?movieNo=[0-9]\\+,\\0\\n,g" | tee "$i-mlist-pre" | \
	sed -u -n "s,^.*\\(http://nowrunning\\.com/.*?movieNo=[0-9]\\+\\).*,\\1,pg" | tee "$i-mlist" | \
	wget -q -i - -O - 2> /dev/null | tee "$i-mhtml" | \
	sed -u -n "s,^.*src=\".*/\\([^\\/]\\+\\)/thumb-still\\([0-9]\\+\\).jpg\".*,http://nowrunning.com/comingsoon/\\1/still\\2.jpg,p" | tee "$i-ilist" | \
	distcmd 10 wget -c -x -o "$i-wpic{}.log" -i -
done
