#!/bin/env zsh
# Pauses mpd if necessary to play some file, and then resumes.

[ -z "$MPD_HOST" ] && MPD_HOST=127.0.0.1
[ -z "$MPD_PORT" ] && MPD_PORT=6600

zmodload zsh/net/tcp
ztcp "$MPD_HOST" "$MPD_PORT"
FD=$REPLY

echo status >&$FD
if [ x"$(grep -m1 'state: ' <&$FD)" = 'xstate: play' ]; then
    echo pause 1 >&$FD
    "$@"
    echo pause 0 >&$FD
else
    "$@"
fi

ztcp -c $FD
