#!/bin/env zsh
# Pauses mpd if necessary to play some file, and then resumes.

HOST=$MPD_HOST
[ -z $HOST ] && HOST=127.0.0.1

zmodload zsh/net/tcp
ztcp $HOST 6600
FD=$REPLY

echo status >&$FD
if [ x"$(grep -m1 'state: ' <&$FD)" = 'xstate: play' ]; then
    echo pause 1 >&$FD
    "$@"
    echo pause 0 >&$FD
else
    "$@"
fi

ztcp -c $FD
