#!/usr/bin/perl
# Mirrors a directory to the current directory using symlinks.

use strict;
use warnings;

my $base = shift or die "No base directory specified!";

{
    local $/ = '/';
    chomp $base;
}

my $opt = shift;
my $flatten = undef;

$flatten = 1 if $opt && $opt eq 'flat';

unless ($flatten) {
    system 'find '.$base.' -type d -mindepth 1 -printf "%P\0" | \
xargs -0 install -d';
    $? and die "Unable to install directories: $?";
}

open FILES, 'find '.$base.' -type f -mindepth 1 -printf "%P\n" |';

while (<FILES>) {
    chomp;
    my $rel = $_;
    s/\//!/ if $flatten;
    symlink "$base/$rel", $_;
}
close FILES;
