#!/bin/bash
# Queues TamilNapster music downloads on d4x.

opts=()
[ -n "$3" ] && opts=(-d "$3")

for ((i=$1;i<=$2;i++)); do
    url="http://www.tamilnapster.com/download.php?id=$i"
    d4x "${opts[@]}" "$url"
    fi
done
