#!/bin/sh
# Executes a command with its first argument pushed after all the remaining
# arguments, to facilitate use in programs like xargs.

# local cmd to

if [ $# -lt 2 ]; then
    echo Usage: $0 '<command>' '<last-arg>' args... >&2
    exit 1
fi

cmd="$1"
to="$2"

shift 2

exec "$cmd" "$@" "$to"
